[package]
name = "dns-core"
version = "0.1.0"
edition = "2024"

[dependencies]
punycode = "0.4.1"


[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "benchmark"
harness = false

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3