[package]
name = "dns-core"
version = "0.1.0"
edition = "2021"

[dependencies]
punycode = "0.4.1"
rand = "0.9.0-beta.3"
generic-array = "1.2.0"
likely_stable = "0.1"


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3