name: Rust

on:
  push:
    branches: [ "performance" ]
  pull_request:
    branches: [ "performance" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Run-RPS_DNS-on-Ubuntu:
    name: Run RPS-DNS on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set nightly
      run: rustup override set nightly
    - name: Build
      run: cargo build  --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Bench
      run: cargo bench --bench benchmark

  Run-RPS_DNS-on-Windows:
    name: Run RPS-DNS on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set nightly
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Bench
      run: cargo bench --bench benchmark

  Run-RPS_DNS-on-Macos:
    name: Run RPS-DNS on Macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set nightly
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Bench
      run: cargo bench --bench benchmark
      
